### PR TITLE
New stan syntax and tags

### PR DESCRIPTION
**Pull request by MansMeg**
The PR includes:
- Updated the stan syntax to 2.26 
- Cleaned up the tags structures. 
- All posteriors has been checked to compile and runs

### CODE REVIEW

**Comment by paul-buerkner** [comment]
I am afraid I won't have the time for full code checking at the moment. Is there something you would like me to take a look at specificially?

**Comment by MansMeg** [comment]
Sorry for my late reply. I updated all the syntax using the stance compiler and checked that all models works to compile and run so I would just skim through quickly and see if you see anything crazy. 

I also polished the tags based on discussion with aki to formalize that a little more. You can see the keywords here:
doc/KEYWORDS.md
That might be good to get extra eyes on.

We have also discussed better ways to assess convergence for reference posteriors (that are less hacky) in:
doc/REFERENCE_POSTERIOR_DEFINITION.md
That might also be good to just look through.

**Comment by paul-buerkner** [comment]
I am currently super busy with teaching and grant writing. If you want to merge it this or next week, perhaps already merge without my feedback. Sorry for being so slow with this right now :-(

**Comment by MansMeg** [comment]
No problem @paul-buerkner . Maybe @avehtari could take a quick look if something is missing.

**Review by avehtari — APPROVED** [review]
I made some edits to md files. It would have been better to use canonicalizer with the option that would have changed only the syntax and not make additional white space changes. Now there were too many files with only white space changes and I didn't have time check changes that matter. If the new code did run and the results did not change, I expect no problems.

**Pull request merged**
