### PR TITLE
Update python stan methods

### PR DESCRIPTION
**Pull request by ahartikainen**
Add backend options for stan framework. (`"pystan", "pystan2", "cmdtanpy"`)

Add CmdStanPy as the default Stan backend.

Change code to work with PyStan (3+).

Adds `posteriordb.STAN_BACKEND` "global" variable that is used automatically by `posterior` class.

To change this value users can call `posteriordb.change_stan_backend` function which accepts `{"cmdstanpy", "pystan", "pystan2"}`

### CODE REVIEW

**Comment by ahartikainen** [comment]
Should we add tests for different backends + pymc3 model?

**Comment by MansMeg** [comment]
The R tests are failing now of other reasons so skip them for now.

Yes. I think it would be good to have a backend to test PyMC3 models (and different backends). I'm not sure how many such models we have right now?

But I guess 8schools is sufficient for this?

**Comment by ahartikainen** [comment]
Yes, 8school is fine.

**Comment by MansMeg** [comment]
Do you want to add that or should I merge it as is and then put it up as an issue?

**Comment by ahartikainen** [comment]
Let's add some tests for this PR.

**Comment by MansMeg** [comment]
Did you want to add some tests here or should I merge it? Im going to start to move the python code to the python repo so it would be great to be able to move it.

**Comment by ahartikainen** [comment]
Oh yes, I have not had time to make these tests. So let's merge and create new repos. I can think about tests after that.

**Comment by MansMeg** [comment]
No problem! Then Ill take it from here.

**Pull request merged**
